Don't encrypt swap partitions
When encrypting the home directory:

 - Due to a bug in ecryptfs-utils/ubiquity, we ended up with no swap partitions at all (https://bugs.launchpad.net/ubuntu/+source/ecryptfs-utils/+bug/953875)
 - Similar to /tmp and /var/user, swap hosts temporary data. Full protection requires full disk encryption, so encrypting the swap only isn't really a requirement here.
 - Hibernation isn't functional with encrypted swap
 - Multiple OSes using the same swap can lead to Mint being unable to boot (this is mostly because Ubiquity doesn't tell the user the swap is encrypted)
 - The installer mentions the encryption of the home directory, but not of the swap

diff --git a/d-i/source/user-setup/user-setup-apply b/d-i/source/user-setup/user-setup-apply
--- a/d-i/source/user-setup/user-setup-apply
+++ b/d-i/source/user-setup/user-setup-apply
@@ -168,13 +168,13 @@ if [ "$RET" = true ] && ! is_system_user; then
 		else
 			$log $chroot $ROOT udevadm settle
 		fi
-		if ! $log $chroot $ROOT ecryptfs-setup-swap -f -n; then
-			echo "ecryptfs-setup-swap failed." >&2
-			db_input critical user-setup/encrypt-home-failed || true
-			db_go || true
-			ENCRYPT_HOME="false"
-			ENCRYPT_HOME_OPT=
-		fi
+		#if ! $log $chroot $ROOT ecryptfs-setup-swap -f -n; then
+		#	echo "ecryptfs-setup-swap failed." >&2
+		#	db_input critical user-setup/encrypt-home-failed || true
+		#	db_go || true
+		#	ENCRYPT_HOME="false"
+		#	ENCRYPT_HOME_OPT=
+		#fi
 		if $umountproc; then
 			$log $chroot $ROOT umount /proc
 		fi
