Version 2.4.8 (Ubuntu 10.10 Maverick Merkaat - stable release)

diff --git a/d-i/source/apt-setup/generators/50mirror b/d-i/source/apt-setup/generators/50mirror
--- a/d-i/source/apt-setup/generators/50mirror
+++ b/d-i/source/apt-setup/generators/50mirror
@@ -112,12 +112,12 @@ if [ -e /cdrom/.disk/base_installable ] || [ "$OVERRIDE_BASE_INSTALLABLE" ]; the
 	fi
 
 	while true; do
-		RET=0
-		choose-mirror -n || RET=$?	# no progress bar
+		CODE=0
+		choose-mirror -n || CODE=$?	# no progress bar
 		db_capb backup progresscancel
-		if [ $RET -eq 0 ]; then
+		if [ $CODE -eq 0 ]; then
 			break
-		elif [ $RET -eq 10 ]; then
+		elif [ $CODE -eq 10 ]; then
 			# User backed out of choose-mirror
 			db_input critical apt-setup/no_mirror
 			db_go || exit 10
@@ -127,8 +127,8 @@ if [ -e /cdrom/.disk/base_installable ] || [ "$OVERRIDE_BASE_INSTALLABLE" ]; the
 				exit 1
 			fi
 		else
-			logger -t apt-setup "choose-mirror failed with error code $RET"
-			exit $RET
+			logger -t apt-setup "choose-mirror failed with error code $CODE"
+			exit $CODE
 		fi
 	done
 fi
diff --git a/d-i/source/flash-kernel/debian/flash-kernel-installer.postinst b/d-i/source/flash-kernel/debian/flash-kernel-installer.postinst
--- a/d-i/source/flash-kernel/debian/flash-kernel-installer.postinst
+++ b/d-i/source/flash-kernel/debian/flash-kernel-installer.postinst
@@ -17,15 +17,40 @@ error() {
 }
 
 findfs () {
-	mount | grep "on /target${1%/} " | cut -d' ' -f1
+	mount | grep "on /target${1%/} " | tail -n1 | cut -d' ' -f1
 }
 
 # Are we writing to flash or constructing an image on disk?
 write_to_flash() {
 	case "$machine" in
-		"Buffalo Linkstation Pro/Live" | "Buffalo/Revogear Kurobox Pro" | "GLAN Tank" | "HP Media Vault mv2120" | "Marvell DB-MV88F6781-BP Development Board")
+		"Buffalo Linkstation Pro/Live")
 			return 1
 		;;
+		"Buffalo/Revogear Kurobox Pro")
+			return 1
+		;;
+		"GLAN Tank")
+			return 1
+		;;
+		"HP Media Vault mv2120")
+			return 1
+		;;
+		"Marvell OpenRD Base Board")
+			return 1
+		;;
+		"Marvell OpenRD Client Board")
+			return 1
+		;;
+		"Marvell SheevaPlug Reference Board")
+			return 1
+		;;
+		"Marvell eSATA SheevaPlug Reference Board")
+			return 1
+		;;
+		"Marvell DB-MV88F6781-BP Development Board")
+			return 1
+		;;
+		# Assume that we write to flash for all other devices
 		*)
 			return 0
 		;;
@@ -34,6 +59,30 @@ write_to_flash() {
 
 machine=$(grep "^Hardware" /proc/cpuinfo | sed 's/Hardware\s*:\s*//')
 
+dove_flash_kernel_installer() {
+	in-target update-initramfs -u || true
+	if ! apt-install uboot-mkimage; then
+		error "apt-install uboot-mkimage failed"
+	fi
+
+	# Add the rootfs to the flash-kernel.conf file
+	rootfs=$(findfs /)
+	uuid="$(block-attr --uuid "$rootfs")"
+	echo "rootfs='root=UUID=$uuid'" > /target/etc/flash-kernel.conf
+}
+
+omap_flash_kernel_installer() {
+	in-target update-initramfs -u || true
+
+	if ! apt-install uboot-mkimage; then
+		error "apt-install uboot-mkimage failed"
+	fi
+
+	# Add the u-boot partition to the flash-kernl.conf file
+	# FIXME: figure out how to properly autodetect this
+	echo "UBOOT_PART=/dev/mmcblk0p1" > /target/etc/flash-kernel.conf
+}
+	# Add the rootfs to the flash-kernel.conf file
 if write_to_flash; then
 	db_progress START 0 3 flash-kernel-installer/progress
 else
@@ -49,15 +98,10 @@ if ! apt-install flash-kernel; then
 	error "apt-install flash-kernel failed"
 fi
 
-# Set up flash-kernel to run on kernel upgrades.
-if ! grep -q flash-kernel /target/etc/kernel-img.conf; then
-	echo "postinst_hook = flash-kernel" >> \
-		/target/etc/kernel-img.conf
-fi
-
 # Temporarily move flash-kernel out of the way so update-initramfs
-# won't call flash-kernel; otherwise we'd call it twice.
+# won't call flash-kernel; otherwise we might call it twice.
 mv /target/usr/sbin/flash-kernel /target/tmp/flash-kernel.$$
+trap "mv /target/tmp/flash-kernel.$$ /target/usr/sbin/flash-kernel" EXIT HUP INT QUIT TERM
 
 db_progress STEP 1
 
@@ -168,42 +212,37 @@ case "$machine" in
 		fi
 	;;
 	"Marvell DB-MV88F6781-BP Development Board")
+		dove_flash_kernel_installer
+	;;
+	"OMAP3 Beagle Board")
+	omap_flash_kernel_installer
+	;;
+	"Marvell OpenRD Base Board" | "Marvell OpenRD Client Board" | "Marvell SheevaPlug Reference Board" | "Marvell eSATA SheevaPlug Reference Board")
 		in-target update-initramfs -u || true
 		if ! apt-install uboot-mkimage; then
 			error "apt-install uboot-mkimage failed"
 		fi
-
-		# Add the rootfs to the flash-kernel.conf file
-		rootfs=$(findfs /)
-		uuid="$(block-attr --uuid "$rootfs")"
-		echo "rootfs='root=UUID=$uuid'" > /target/etc/flash-kernel.conf
 	;;
-	"OMAP3 Beagle Board")
-		if ! apt-install uboot-mkimage; then
-			error "apt-install uboot-mkimage failed"
-		fi
-		if ! apt-install uboot-envtools; then
-			error "apt-install uboot-envtools failed"
-		fi
-		rootfs=$(findfs /)
-		uuid="$(block-attr --uuid "$rootfs")"
-		cmdline="root=UUID=$uuid ro quiet splash vram=12M omapfb.mode=dvi:1280x720MR-16@60 fixrtc"
-		bootcmd="nand read 80000000 280000 400000;nand read 81600000 680000 1000000;bootm 80000000 81600000"
-		# create a default config for uboot-envtools
-		echo "/dev/mtd2 0x0000 0x20000 0x20000" > /target/etc/fw_env.config
-		# set proper NAND boot defaults
-		in-target fw_setenv bootcmd "${bootcmd}"
-		in-target fw_setenv bootargs "${cmdline}"
-		in-target fw_setenv bootdelay 3
-    ;;
 	"Thecus N2100" | "Thecus N4100")
 		in-target update-initramfs -u || true
 	;;
-	"QNAP TS-109/TS-209" | "QNAP TS-409")
+	"QNAP TS-109/TS-209" | "QNAP TS-119/TS-219" | "QNAP TS-409" | "QNAP TS-41x")
 		in-target update-initramfs -u || true
 		if ! apt-install uboot-mkimage; then
 			error "apt-install uboot-mkimage failed"
 		fi
+	;;
+	"Lanner EM7210")
+		in-target update-initramfs -u || true
+	;;
+	*)
+		case "`archdetect`" in
+			"arm*/dove")
+				dove_flash_kernel_installer
+			;;
+			"arm*/omap" | "arm*/omap4")
+				omap_flash_kernel_installer
+			esac
 	;;
 esac
 
@@ -214,6 +253,7 @@ else
 	db_progress INFO flash-kernel-installer/generating_image
 fi
 
+trap - EXIT HUP INT QUIT TERM
 mv /target/tmp/flash-kernel.$$ /target/usr/sbin/flash-kernel
 
 # We need the udev /dev which has the MTD devices
diff --git a/d-i/source/grub-installer/grub-installer b/d-i/source/grub-installer/grub-installer
--- a/d-i/source/grub-installer/grub-installer
+++ b/d-i/source/grub-installer/grub-installer
@@ -75,14 +75,10 @@ grub_serial_console() {
 
 serial="$(get_serial_console)"
 
-## This is copied from update-grub; we've requested that it be moved
-## to a utility or shell library
-## TODO: replace this with grub-probe
 device_map=$ROOT/boot/grub/device.map
 
 # Usage: convert os_device
 # Convert an OS device to the corresponding GRUB drive
-# This part is OS-specific
 convert () {
 	# Adjust the device map to add a SATA RAID array.
 	if [ "$grub_version" = grub ] && [ "$frtype" = "sataraid" ] && type dmraid >/dev/null 2>&1; then
@@ -238,6 +234,11 @@ device_to_id()
 			return 0
 		fi
 	done
+	# Fall back to the plain device name if there's no by-id link for it.
+	if [ -e "$1" ]; then
+		echo "$1"
+		return 0
+	fi
 	return 1
 }
 
@@ -380,7 +381,10 @@ case $ARCH in
 		grub_package="grub"
 	fi
 	;;
-    i386/*|amd64/*|lpia/*)
+    i386/efi|amd64/efi)
+	grub_package="grub-efi"
+	;;
+    i386/*|amd64/*)
 	# On PC/BIOS, default to GRUB Legacy
 	grub_package="grub"
 	;;
@@ -408,6 +412,12 @@ case "$frtype:$bootfstype:$bootfslabel:$grub_package" in
     *:ufs:*:*)
 	# Booting from UFS requires grub2
 	grub_package="grub-pc"
+	;;
+    *:ext2fs:*:grub-pc | *:xfs:*:grub-pc)
+    	# Booting ext2fs or xfs using grub2 works
+        ;;
+    *:*:*:grub-efi*)
+	# No reasonable alternative to GRUB here
 	;;
     *:*:*:*)
 	db_subst grub-installer/grub_not_mature_on_this_platform ARCH $ARCH
@@ -503,33 +513,36 @@ db_progress INFO grub-installer/progress/step_install
 # to grub legacy, or vice-versa
 case "$grub_package" in
     grub)
-	log-output -t grub-installer $chroot $ROOT dpkg -P grub-pc
+	log-output -t grub-installer $chroot $ROOT dpkg -P grub-pc grub-efi grub-efi-amd64 grub-efi-ia32
 	;;
     grub-pc)
-	log-output -t grub-installer $chroot $ROOT dpkg -P grub grub-legacy
-	# os-prober is only a Recommends so isn't installed by apt-install,
-	# but we make sure it's installed since it does a better
-	# job than the otheros script.
-	apt-install os-prober || true
+	log-output -t grub-installer $chroot $ROOT dpkg -P grub grub-legacy grub-efi grub-efi-amd64 grub-efi-ia32
+	;;
+    grub-efi)
+	log-output -t grub-installer $chroot $ROOT dpkg -P grub grub-legacy grub-pc
 	;;
 esac
 
 exit_code=0
+inst_package=$grub_package
 case "$grub_package" in
     grub)
-	if ! apt-install grub-legacy ; then
+	if apt-install --no-recommends grub-legacy ; then
+		inst_package=grub-legacy
+	else
 		apt-install $grub_package || exit_code=$? 
 	fi
 	;;
    *)
+	# Will pull in os-prober based on global setting for Recommends
 	apt-install $grub_package || exit_code=$? 
 	;;
 esac
 
 if [ $exit_code -ne 0 ] ; then
 	db_progress STOP
-	info "Calling 'apt-install $grub_package' failed"
-	db_subst grub-installer/apt-install-failed GRUB "$grub_package"
+	info "Calling 'apt-install $inst_package' failed"
+	db_subst grub-installer/apt-install-failed GRUB "$inst_package"
 	db_input critical grub-installer/apt-install-failed || true
 	if ! db_go; then
 		exit 10 # back up to menu
@@ -537,7 +550,7 @@ if [ $exit_code -ne 0 ] ; then
 	exit 1
 fi
 
-grub_debian_version="$($chroot $ROOT dpkg-query -W -f '${Version}' $grub_package)"
+grub_debian_version="$($chroot $ROOT dpkg-query -W -f '${Version}' $inst_package)"
 
 if [ "$frtype" = multipath ]; then
 	$chroot $ROOT umount /proc
@@ -626,7 +639,7 @@ fi
 # turned into a stable by-id name is better.
 default_bootdev_os="$($chroot $ROOT grub-mkdevicemap --no-floppy -m - | head -n1 | cut -f2)"
 if [ "$default_bootdev_os" ]; then
-	default_bootdev="$default_bootdev_os"
+	default_bootdev="$($chroot $ROOT readlink -f "$default_bootdev_os")"
 else
 	default_bootdev='(hd0)'
 fi
@@ -637,8 +650,12 @@ fi
 # boot device.
 cdsrc=$(mount | grep "on /cdrom " | cut -d' ' -f1)
 cdfs=$(mount | grep "on /cdrom " | cut -d' ' -f5)
-if ([ "$cdsrc" = "$default_bootdev" ] || [ "$default_bootdev" = '(hd0)' ]) && \
-   [ -n "$cdfs" ] && [ "$cdfs" != "iso9660" ]; then
+if [ "$grub_package" = grub-efi ]; then
+	# No need for install device selection on EFI.
+	bootdev=efi-dummy
+	state=3
+elif ([ "$cdsrc" = "$default_bootdev" ] || [ "$default_bootdev" = '(hd0)' ]) && \
+     [ -n "$cdfs" ] && [ "$cdfs" != "iso9660" ]; then
 	db_fget grub-installer/bootdev seen
 	if [ "$RET" != true ]; then
 		bootfs=$(findfs /boot)
@@ -673,6 +690,9 @@ elif [ "$grub_version" = grub2 ] && [ "$frtype" = mdadm ]; then
 	else
 		default_bootdev="$bootfs_nodevfs"
 	fi
+	db_set grub-installer/bootdev "$default_bootdev"
+elif [ "$frdev" ]; then
+	default_bootdev="$frdev"
 	db_set grub-installer/bootdev "$default_bootdev"
 fi
 
@@ -716,7 +736,7 @@ while : ; do
 			fi
 			state=2
 		fi
-	else
+	elif [ "$state" = 2 ]; then
 		db_input critical grub-installer/bootdev || true
 		if ! db_go; then
 			if [ "$q" ]; then
@@ -737,6 +757,8 @@ while : ; do
 			fi
 			break
 		fi
+	else
+		break
 	fi
 done
 
@@ -815,11 +837,22 @@ if [ -z "$frdisk" ] || [ "$grub_version" = grub2 ]; then
 			umountsys=:
 		fi
 
-		info "Running $chroot $ROOT grub-install $grub_install_params \"$bootdev\""
-		if log-output -t grub-installer $chroot $ROOT grub-install $grub_install_params "$bootdev"; then
+		CODE=0
+		if [ "$grub_package" = grub-efi ]; then
+			info "Running $chroot $ROOT grub-install $grub_install_params"
+			log-output -t grub-installer $chroot $ROOT grub-install $grub_install_params || CODE=$?
+		else
+			info "Running $chroot $ROOT grub-install $grub_install_params \"$bootdev\""
+			log-output -t grub-installer $chroot $ROOT grub-install $grub_install_params "$bootdev" || CODE=$?
+		fi
+		if [ "$CODE" = 0 ]; then
 			info "grub-install ran successfully"
 		else
-			error "Running 'grub-install $grub_install_params \"$bootdev\"' failed."
+			if [ "$grub_package" = grub-efi ]; then
+				error "Running 'grub-install $grub_install_params' failed."
+			else
+				error "Running 'grub-install $grub_install_params \"$bootdev\"' failed."
+			fi
 			db_subst grub-installer/grub-install-failed BOOTDEV "$bootdev"
 			db_input critical grub-installer/grub-install-failed || [ $? -eq 30 ]
 			db_go || true
@@ -1135,6 +1168,15 @@ if [ "$grub_version" = grub ]; then
 	fi
 fi
 
+if db_get grub-installer/timeout
+then
+	# Check whether it's a number
+	if [ "$RET" -eq "$RET" ] 2> /dev/null
+	then
+		timeout="$RET"
+	fi
+fi
+
 if [ -z "$hide_menu" ] && [ -s /tmp/os-probed ]; then
 	# Other operating systems are installed, so show the menu by default
 	# and raise the timeout.
@@ -1145,6 +1187,18 @@ if [ -z "$hide_menu" ] && [ -s /tmp/os-probed ]; then
 	else
 		sed -i 's/^GRUB_HIDDEN_TIMEOUT=.*/#&/;
 			s/^GRUB_TIMEOUT=.*/GRUB_TIMEOUT=10/' \
+			$ROOT/etc/default/grub
+		update_grub # propagate to grub.cfg
+	fi
+elif [ -n "$timeout" ]; then
+	# Leave a slight delay
+	if [ "$grub_version" = grub ]; then
+		sed -i 's/^hiddenmenu[[:space:]]*$/#hiddenmenu/;
+			s/^\(timeout[[:space:]][[:space:]]*\).*/\1'$timeout'/' \
+			$ROOT/boot/grub/menu.lst
+	else
+		sed -i 's/^GRUB_HIDDEN_TIMEOUT=.*/#&/;
+			s/^GRUB_TIMEOUT=.*/GRUB_TIMEOUT='$timeout'/' \
 			$ROOT/etc/default/grub
 		update_grub # propagate to grub.cfg
 	fi
@@ -1285,7 +1339,8 @@ db_progress INFO grub-installer/progress/step_update_etc
 if [ -e $ROOT/etc/kernel-img.conf ] ; then
 	sed -i 's/do_bootloader = yes/do_bootloader = no/' $ROOT/etc/kernel-img.conf
 fi
-if [ -z "$(grep update-grub $ROOT/etc/kernel-img.conf)" ]; then
+if [ ! -e $ROOT/etc/kernel/postinst.d/zz-update-grub ] && \
+   [ -z "$(grep update-grub $ROOT/etc/kernel-img.conf)" ]; then
 	(
 		echo "postinst_hook = update-grub"
 		echo "postrm_hook   = update-grub"
