20.04.15 (Focal)

diff --git a/scripts/simple-plugins b/scripts/simple-plugins
--- a/scripts/simple-plugins
+++ b/scripts/simple-plugins
@@ -3,18 +3,30 @@ set -e
 
 . /usr/share/debconf/confmodule
 if [ "$1" = "prepare" ]; then
+    FREEONLY="--free-only"
+    NOOEM=""
     db_input high ubiquity/use_nonfree || true
     db_get ubiquity/use_nonfree
     if [ "$RET" = "true" ]; then
-        env -u DEBIAN_HAS_FRONTEND -u DEBCONF_REDIR \
-            DEBCONF_DB_REPLACE=configdb DEBCONF_DB_OVERRIDE="Pipe{infd:none outfd:none}" \
-            ubuntu-drivers autoinstall --package-list /run/ubuntu-drivers.autoinstall || \
-		logger -t ubiquity "ubuntu-drivers autoinstall failed with code: $?"
+	    FREEONLY=""
     fi
+    db_input high ubiquity/install_oem || true
+    db_get ubiquity/install_oem
+    if [ "$RET" = "false" ]; then
+	    NOOEM="--no-oem"
+    fi
+
+    rm -f /run/ubuntu-drivers.autoinstall
+    ubuntu-drivers install $FREEONLY $NOOEM --package-list /run/ubuntu-drivers.autoinstall || \
+        logger -t ubiquity "ubuntu-drivers install failed with code: $?"
+
     db_input high ubiquity/secureboot_key || true
     db_get ubiquity/secureboot_key
     if [ -n "$RET" ]; then
-        printf '%s\n%s\n' "$RET" "$RET" | mokutil --disable-validation >/dev/null || true
+        mkdir -p /var/lib/shim-signed/mok
+        /usr/lib/ubiquity/shim-signed/update-secureboot-policy --new-key
+        printf '%s\n%s\n' "$RET" "$RET" | mokutil --import /var/lib/shim-signed/mok/MOK.der >/dev/null || true
+        mokutil --timeout -1 >/dev/null || true
     fi
     # Always clear secureboot key.
     db_set ubiquity/secureboot_key ''
